export const processStages = [
  { name: "Discover", graphicStage: "sketch", title: "Start with the right questions.", description: "We understand your business, your customers and what the website needs to achieve.", deliverable: "Business goals & customer insights" },
  { name: "Define", graphicStage: "wireframe", title: "Give every page a purpose.", description: "We structure the content, plan the user journey and create a clear design direction.", deliverable: "Website strategy & wireframes" },
  { name: "Develop", graphicStage: "high-fidelity", title: "Bring the experience to life.", description: "We bring the design to life with clean, modern interfaces and a seamless development process.", deliverable: "Design & website development" },
  { name: "Deliver", graphicStage: "finished", title: "Launch with confidence.", description: "We launch your website and make sure it’s fast, secure and ready to grow your business.", deliverable: "Testing, launch & handover" },
] as const;

export const projects = [
  { id: "rom-africa", name: "Rom Africa Safaris", category: "Travel & hospitality", image: "/assets/work/rom-africa-homepage.png", imageWidth: 3418, imageHeight: 1890, preview: "screenshot", alt: "Rom Africa Safaris homepage with giraffes, safari planning and booking controls", description: "A clearer path from safari inspiration to a personal itinerary.", focus: "A travel concept exploring how destination storytelling and simple enquiry paths can help travellers plan with confidence.", direction: "Immersive photography, considered trip information, and a clear next step for each journey." },
  { id: "ridgeview", name: "Ridgeview Properties", category: "Real estate", image: "/assets/work/property-concept.webp", imageWidth: 1536, imageHeight: 1024, preview: "concept", alt: "Illustrative property concept with a modern home and landscaped garden", description: "Helping home seekers find a place they can picture themselves in.", focus: "A property concept exploring a more useful browsing experience, with the details buyers need to decide what to view.", direction: "Generous property imagery, clear information hierarchy, and a direct route to booking a viewing." },
  { id: "carlux-kenya", name: "CarLux Kenya", category: "Automotive", image: "/assets/work/carlux-kenya-homepage.png", imageWidth: 3418, imageHeight: 1890, preview: "screenshot", alt: "CarLux Kenya homepage with a silver Mercedes-Benz SUV and vehicle search controls", description: "A considered digital showroom for a more confident next purchase.", focus: "An automotive concept exploring how a digital showroom can support the decision to enquire about a vehicle.", direction: "Focused vehicle presentations, accessible specifications, and straightforward enquiries." },
] as const;
