export const processStages = [
  { name: "Discover", graphicStage: "sketch", title: "Start with the right questions.", description: "We get to know your business, your customers, and what stands between them. Together, we find what your website needs to do better.", deliverable: "Business goals & customer insights" },
  { name: "Define", graphicStage: "wireframe", title: "Give every page a purpose.", description: "We turn what we learn into a clear plan: the right pages, the right content, and a straightforward path from first visit to enquiry.", deliverable: "Website strategy & wireframes" },
  { name: "Develop", graphicStage: "high-fidelity", title: "Bring the experience to life.", description: "We shape the visual direction and build a responsive website. Every detail, from the first headline to the final click, works toward your goals.", deliverable: "Design & website development" },
  { name: "Deliver", graphicStage: "finished", title: "Launch with confidence.", description: "We test across devices, refine the details, and prepare you to manage your website. Then we launch, with support for what comes next.", deliverable: "Testing, launch & handover" },
] as const;

export const projects = [
  { id: "rom-africa", name: "Rom Africa Safaris", category: "Travel & hospitality", image: "/assets/work/safari-concept.webp", alt: "Illustrative safari concept with elephants in golden grassland", description: "A clearer path from safari inspiration to a personal itinerary.", focus: "A travel concept exploring how destination storytelling and simple enquiry paths can help travellers plan with confidence.", direction: "Immersive photography, considered trip information, and a clear next step for each journey." },
  { id: "ridgeview", name: "Ridgeview Properties", category: "Real estate", image: "/assets/work/property-concept.webp", alt: "Illustrative property concept with a modern home and landscaped garden", description: "Helping home seekers find a place they can picture themselves in.", focus: "A property concept exploring a more useful browsing experience, with the details buyers need to decide what to view.", direction: "Generous property imagery, clear information hierarchy, and a direct route to booking a viewing." },
  { id: "autolux", name: "Autolux Kenya", category: "Automotive", image: "/assets/work/automotive-concept.webp", alt: "Illustrative automotive concept with a graphite sports coupe", description: "A considered digital showroom for a more confident next purchase.", focus: "An automotive concept exploring how a digital showroom can support the decision to enquire about a vehicle.", direction: "Focused vehicle presentations, accessible specifications, and straightforward enquiries." },
] as const;
